### ISSUE TITLE
running build.sh results in malformed http response

### ISSUE THREAD

**Issue by hslee16** [StartupML/jetpack#15]
Running build.sh with any package results in something similar to the following:

./build.sh julia
Preparing to build Macintosh prerequisites...done!
Starting builds
Sending build context to Docker daemon 5.632 kB
Sending build context to Docker daemon 
FATA[0000] Post http://192.168.59.103:2376/v1.16/build?rm=1&t=startupml%2Fjulia: malformed HTTP response "\x15\x03\x01\x00\x02\x02\x16" 

This is on OS X.

**Comment by arshak** [comment]
Can you send me your docker info output?

**Comment by hslee16** [comment]
Running docker info results in:

FATA[0000] Get http://192.168.59.103:2376/v1.16/info: malformed HTTP response "\x15\x03\x01\x00\x02\x02". Are you trying to connect to a TLS-enabled daemon without TLS?

After installing boot2docker, I had to set the DOCKER_HOST environment variable to the vm used by boot2docker. In my case 192.168.59.103:2376.
The question is, why is docker using the same address to look for images?

**Comment by arshak** [comment]
Can you make sure you are in boot2docker?  Goto spotlight and type
boot2docker.

If it doesn't work please send the output of that window.

**Comment by hslee16** [comment]
cool, works from boot2docker. Thank you.
