### ISSUE TITLE
gfx_information.sh in torch7 folder missing

### ISSUE THREAD

**Issue by JulianHill** [StartupML/jetpack#19]
The gfx_information.sh file is missing in the torch7 folder and so the command 
```
ADD gfx_information.sh /usr/bin/gfx_information.sh
```
in the Dockerfile stops the build process.
After adding the file from here it works: https://github.com/jbenjos/torch7-docker/blob/master/gfx_information.sh

Regards

**Comment by arshak** [comment]
file has been added
